name: Code Formatting

on:
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: psf/black@stable
